name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-image-dev && cargo test --verbose
